// packages/infrastructure/angular/RouteManager/RouteHandler.ts
import { RouteRepository } from '@c-a-f/core';
import { Injectable } from '@angular/core';
import type { Router } from '@angular/router';

/**
 * Angular adapter for the core RouteRepository.
 * Uses Angular Router so RouteManager from @c-a-f/core works in Angular apps.
 * Prefer `injectRouteRepository()` for a consistent API with React/Vue.
 */
@Injectable({ providedIn: 'root' })
export class RouteHandler implements RouteRepository {
  constructor(private router: Router) {}

  get currentRoute(): string {
    return this.router.url;
  }

  change(route: string): void {
    this.router.navigateByUrl(route);
  }
}

// packages/infrastructure/react/RouteManager/RouteHandler.ts
import { RouteRepository } from "@caf/core";
import { useNavigate, useLocation } from "react-router-dom";

export class RouteHandler implements RouteRepository {
    private navigate = useNavigate()

    constructor() {
        this.watchCurrentRoute()
    }

    currentRoute: string = ''

    change(route: string) {
        this.navigate(route)
    }

    watchCurrentRoute() {
        const { pathname } = useLocation()
        this.currentRoute = pathname
    }


}
